import { Article, Farmer, MarketProduct, Post, PricePrediction, Product } from "@/types";

export const pricePredictions: PricePrediction[] = [
  {
    crop: "Maize",
    current: "UGX 850/kg",
    predicted: "UGX 920/kg",
    trend: "up",
    confidence: 87,
  },
  {
    crop: "Tomatoes",
    current: "UGX 1,200/kg",
    predicted: "UGX 1,050/kg",
    trend: "down",
    confidence: 72,
  },
  {
    crop: "Beans",
    current: "UGX 2,300/kg",
    predicted: "UGX 2,500/kg",
    trend: "up",
    confidence: 91,
  },
];

export const farmers: Farmer[] = [
  {
    id: 1,
    name: "Okello James",
    avatar: "OJ",
    verified: true,
    badge: "Grains",
    location: "Gulu District",
    rating: 4.8,
    produce: ["Maize", "Soya", "Millet"],
    online: true,
    reviews: 31,
  },
  {
    id: 2,
    name: "Nakato Sarah",
    avatar: "NS",
    verified: true,
    badge: "Vegetables",
    location: "Wakiso District",
    rating: 4.9,
    reviews: 31,
    produce: ["Tomatoes", "Onions", "Pepper"],
  },
  {
    id: 3,
    name: "Okello James",
    avatar: "OJ",
    verified: true,
    badge: "Grains",
    location: "Gulu District",
    rating: 4.8,
    produce: ["Maize", "Soya", "Millet"],
    online: true,
    reviews: 31,
  },
  {
    id: 4,
    name: "Nakato Sarah",
    avatar: "NS",
    verified: true,
    badge: "Vegetables",
    location: "Wakiso District",
    rating: 4.9,
    produce: ["Tomatoes", "Onions", "Pepper"],
    reviews: 31,
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Grade A Maize",
    farmer: "Okello James",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg", // Keeping both image keys for compatibility
    category: "Grains",
    district: "Gulu",
    rating: 4.8,
    price: 850,
    priceValue: 850,
    unit: "kg",
    qty: 5000,
    qtyDisplay: "5,000 kg available", // Mapped from your 'qty' string
    badge: "Fresh",
    fresh: true,
    verified: true,
    img: "",
  },
  {
    id: "2",
    name: "Supa Rice",
    farmer: "Auma Sarah",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "Grains",
    district: "Bugiri",
    rating: 4.6,
    price: 3800,
    priceValue: 3800,
    unit: "kg",
    qty: 1200,
    qtyDisplay: "1,200 kg available",
    badge: "Top Rated",
    fresh: false,
    verified: true,
    img: "",
  },
  {
    id: "3",
    name: "Sweet Potatoes",
    farmer: "Mugisha Samuel",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "Tubers",
    district: "Soroti",
    rating: 4.3,
    price: 1200,
    priceValue: 1200,
    unit: "kg",
    qty: 800,
    qtyDisplay: "800 kg available",
    badge: "Fresh",
    fresh: true,
    verified: false,
    img: "",
  },
  {
    id: "4",
    name: "Red Onions",
    farmer: "Nansubuga Jane",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "Vegetables",
    district: "Wakiso",
    rating: 4.9,
    price: 4000,
    priceValue: 4000,
    unit: "kg",
    qty: 300,
    qtyDisplay: "300 kg available",
    badge: "Organic",
    fresh: true,
    verified: true,
    img: "",
  },
];

export const posts: Post[] = [
  {
    slug: "soil-health-guide-2025",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "Soil & Crops",
    title: "The Farmer's Complete Guide to Soil Health in 2025",
    excerpt:
      "Understanding NPK ratios, microbial activity, and cover cropping strategies that helped our test plots yield 40% more maize this season.",
    author: "Samuel Ochieng",
    likes: 312,
    comments: 54,
    readTime: "7 min read",
    publishedAt: "2025-02-04",
    id: "1",
  },
  {
    slug: "drip-irrigation-small-farms",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "Irrigation",
    title: "Drip Irrigation on a Budget: A Small Farm Setup Guide",
    excerpt:
      "How a 2-acre vegetable farm in the Rift Valley cut water usage by 60% with a DIY drip system built for under $300.",
    author: "Aisha Mwangi",
    likes: 198,
    comments: 41,
    readTime: "6 min read",
    publishedAt: "2025-02-18",
    id: "2",
  },
  {
    slug: "drone-crop-monitoring",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "AgriTech",
    title: "Using Drones for Crop Monitoring: Is It Worth It?",
    excerpt:
      "We tested three consumer drones over two seasons to see if aerial NDVI imaging actually helps smallholder farmers catch disease early.",
    author: "James Karanja",
    likes: 254,
    comments: 67,
    readTime: "8 min read",
    publishedAt: "2025-03-01",
    id: "3",
  },
  {
    slug: "rotational-grazing-cattle",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "Livestock",
    title: "Rotational Grazing: How We Doubled Pasture Productivity",
    excerpt:
      "A practical breakdown of paddock design, rest periods, and stocking density — and the real numbers from our 50-head cattle operation.",
    author: "Beatrice Njoroge",
    likes: 143,
    comments: 29,
    readTime: "5 min read",
    publishedAt: "2025-03-08",
    id: "4",
  },
  {
    slug: "selling-direct-to-market",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "Business",
    title: "Cutting Out the Middleman: Selling Direct to Urban Markets",
    excerpt:
      "From WhatsApp groups to farm subscription boxes — how three Ugandan farmers increased their net income by 35% without growing more food.",
    author: "David Ssemwanga",
    likes: 389,
    comments: 92,
    readTime: "6 min read",
    publishedAt: "2025-03-15",
    id: "5",
  },
  {
    slug: "composting-at-scale",
    image: "https://i.pinimg.com/736x/11/9c/ea/119cea4b403ddcfcba404b6e58ddff0d.jpg",
    category: "Sustainability",
    title: "Composting at Scale: Turning Waste into Your Best Fertiliser",
    excerpt:
      "A step-by-step system for managing windrow compost on farms of 5–50 acres, including temperature tracking and turning schedules.",
    author: "Grace Akello",
    likes: 176,
    comments: 38,
    readTime: "5 min read",
    publishedAt: "2025-03-20",
    id: "6",
  },
];
