import { Article, Farmer, MarketProduct, PricePrediction, Product } from "@/types";

export const pricePredictions: PricePrediction[] = [
  {
    crop: "Maize",
    current: "UGX 850/kg",
    predicted: "UGX 920/kg",
    trend: "up",
    confidence: 87,
  },
  {
    crop: "Tomatoes",
    current: "UGX 1,200/kg",
    predicted: "UGX 1,050/kg",
    trend: "down",
    confidence: 72,
  },
  {
    crop: "Beans",
    current: "UGX 2,300/kg",
    predicted: "UGX 2,500/kg",
    trend: "up",
    confidence: 91,
  },
]


export const farmers: Farmer[] = [
  {
    id: 1,
    name: "Okello James",
    avatar: "OJ",
    verified: true,
    badge: "Grains",
    location: "Gulu District",
    rating: 4.8,
    produce: ["Maize", "Soya", "Millet"],
    online: true,
    reviews: 31,
  },
  {
    id: 2,
    name: "Nakato Sarah",
    avatar: "NS",
    verified: true,
    badge: "Vegetables",
    location: "Wakiso District",
    rating: 4.9,
    reviews: 31,
    produce: ["Tomatoes", "Onions", "Pepper"],
  },
   {
    id: 3,
    name: "Okello James",
    avatar: "OJ",
    verified: true,
    badge: "Grains",
    location: "Gulu District",
    rating: 4.8,
    produce: ["Maize", "Soya", "Millet"],
    online: true,
    reviews: 31,
  },
  {
    id: 4,
    name: "Nakato Sarah",
    avatar: "NS",
    verified: true,
    badge: "Vegetables",
    location: "Wakiso District",
    rating: 4.9,
    produce: ["Tomatoes", "Onions", "Pepper"],
    reviews: 31,
  },
]

export const products: Product[] = [
  {
    id: 1,
    name: "Grade A Maize",
    farmer: "Okello James",
    img: "🌽",
    badge: "Fresh",
    price: "UGX 850/kg",
    rating: 4.8,
    qty: "5,000 kg available",
  },
  {
    id: 2,
    name: "Fresh Tomatoes",
    farmer: "Nakato Sarah",
    img: "🍅",
    price: "UGX 1,200/kg",
    rating: 4.9,
    qty: "800 kg available",
  },

  {
    id: 3,
    name: "Grade A Maize",
    farmer: "Okello James",
    img: "🌽",
    badge: "Fresh",
    price: "UGX 850/kg",
    rating: 4.8,
    qty: "5,000 kg available",
  },
  {
    id: 4,
    name: "Fresh Tomatoes",
    farmer: "Nakato Sarah",
    img: "🍅",
    price: "UGX 1,200/kg",
    rating: 4.9,
    qty: "800 kg available",
  },
]

//blogs
export const blogs: Article[] = [
  {
    id: 1,
    img: "🌽",
    tag: "Grains",
    title: "How I Increased My Maize Yield by 300% in One Season",
    author: "Okello James",
    readTime: "8 min read",
  },
  {
    id: 2,
    img: "🌦️",
    tag: "Climate",
    title: "Climate Smart Farming for Uganda's Changing Weather",
    author: "Dr. Harriet Mwanje",
    readTime: "12 min read",
  },
]


// src/data/products.ts
// import type { MarketProduct } from "@/pages/marketplace/types"

export const products3: MarketProduct[] = [
  {
    id: 1,
    name: "Grade A Maize",
    farmer: "Okello James",
    img: "🌽",
    badge: "Fresh",
    price: "UGX 850/kg",
    priceValue: 850,
    rating: 4.8,
    qty: "5,000 kg available",
    category: "Grains",
  },
  {
    id: 2,
    name: "Fresh Tomatoes",
    farmer: "Nakato Sarah",
    img: "🍅",
    badge: "Organic",
    price: "UGX 1,200/kg",
    priceValue: 1200,
    rating: 4.9,
    qty: "800 kg available",
    category: "Vegetables",
  },
  {
    id: 3,
    name: "Organic Honey",
    farmer: "Tumuhaise Peter",
    img: "🍯",
    badge: "Premium",
    price: "UGX 25,000/L",
    priceValue: 25000,
    rating: 5.0,
    qty: "200 litres available",
    category: "Cash Crops",
  },
  {
    id: 4,
    name: "Irish Potatoes",
    farmer: "Akello Grace",
    img: "🥔",
    badge: "Fresh",
    price: "UGX 600/kg",
    priceValue: 600,
    rating: 4.7,
    qty: "12,000 kg available",
    category: "Vegetables",
  },
  {
    id: 5,
    name: "Vanilla Pods",
    farmer: "Birungi Joyce",
    img: "🌿",
    badge: "Premium",
    price: "UGX 180,000/kg",
    priceValue: 180000,
    rating: 4.9,
    qty: "50 kg available",
    category: "Cash Crops",
  },
  {
    id: 6,
    name: "Fresh Whole Milk",
    farmer: "Rwabwogo Daniel",
    img: "🥛",
    badge: "Fresh",
    price: "UGX 1,500/L",
    priceValue: 1500,
    rating: 4.8,
    qty: "500 litres available",
    category: "Dairy",
  },
  {
    id: 7,
    name: "Dry Soya Beans",
    farmer: "Otim Robert",
    img: "🫘",
    price: "UGX 1,800/kg",
    priceValue: 1800,
    rating: 4.6,
    qty: "3,000 kg available",
    category: "Grains",
  },
  {
    id: 8,
    name: "Ripe Avocados",
    farmer: "Namukasa Fiona",
    img: "🥑",
    badge: "Organic",
    price: "UGX 500/piece",
    priceValue: 500,
    rating: 4.7,
    qty: "2,400 pieces available",
    category: "Fruits",
  },
  {
    id: 9,
    name: "Sweet Bananas",
    farmer: "Mugisha Collins",
    img: "🍌",
    badge: "Fresh",
    price: "UGX 800/bunch",
    priceValue: 800,
    rating: 4.5,
    qty: "1,200 bunches available",
    category: "Fruits",
  },
  {
    id: 10,
    name: "Arabica Coffee",
    farmer: "Byamugisha Fred",
    img: "☕",
    badge: "Premium",
    price: "UGX 8,200/kg",
    priceValue: 8200,
    rating: 4.9,
    qty: "800 kg available",
    category: "Cash Crops",
  },
  {
    id: 11,
    name: "Red Onions",
    farmer: "Atim Patience",
    img: "🧅",
    price: "UGX 1,100/kg",
    priceValue: 1100,
    rating: 4.4,
    qty: "4,500 kg available",
    category: "Vegetables",
  },
  {
    id: 12,
    name: "Fresh Eggs",
    farmer: "Ssemakula Brian",
    img: "🥚",
    badge: "Fresh",
    price: "UGX 450/piece",
    priceValue: 450,
    rating: 4.8,
    qty: "10,000 pieces available",
    category: "Dairy",
  },
  {
    id: 13,
    name: "Passion Fruits",
    farmer: "Kyomuhendo Amina",
    img: "🍈",
    badge: "Organic",
    price: "UGX 300/piece",
    priceValue: 300,
    rating: 4.6,
    qty: "5,000 pieces available",
    category: "Fruits",
  },
  {
    id: 14,
    name: "Finger Millet",
    farmer: "Oryem Moses",
    img: "🌾",
    price: "UGX 1,400/kg",
    priceValue: 1400,
    rating: 4.5,
    qty: "6,000 kg available",
    category: "Grains",
  },
  {
    id: 15,
    name: "Fresh Ginger",
    farmer: "Namutebi Faith",
    img: "🫚",
    badge: "Organic",
    price: "UGX 3,500/kg",
    priceValue: 3500,
    rating: 4.7,
    qty: "300 kg available",
    category: "Herbs",
  },
  {
    id: 16,
    name: "Pineapples",
    farmer: "Wasswa David",
    img: "🍍",
    badge: "Fresh",
    price: "UGX 1,500/piece",
    priceValue: 1500,
    rating: 4.8,
    qty: "3,000 pieces available",
    category: "Fruits",
  },
  {
    id: 17,
    name: "Groundnuts",
    farmer: "Acen Betty",
    img: "🥜",
    price: "UGX 2,200/kg",
    priceValue: 2200,
    rating: 4.6,
    qty: "2,000 kg available",
    category: "Grains",
  },
  {
    id: 18,
    name: "Dried Chillies",
    farmer: "Ochieng Paul",
    img: "🌶️",
    badge: "Organic",
    price: "UGX 4,500/kg",
    priceValue: 4500,
    rating: 4.5,
    qty: "150 kg available",
    category: "Herbs",
  },
  {
    id: 19,
    name: "Sweet Potatoes",
    farmer: "Nakigozi Rose",
    img: "🍠",
    badge: "Fresh",
    price: "UGX 700/kg",
    priceValue: 700,
    rating: 4.4,
    qty: "8,000 kg available",
    category: "Vegetables",
  },
  {
    id: 20,
    name: "Cocoa Beans",
    farmer: "Tendo Richard",
    img: "🍫",
    badge: "Premium",
    price: "UGX 12,000/kg",
    priceValue: 12000,
    rating: 4.9,
    qty: "500 kg available",
    category: "Cash Crops",
  },
]