import type { Farmer,Product } from "./types"

export const farmers: Farmer[] = [
  {
    id: 1,
    name: "Okello James",
    avatar: "OJ",
    avatarUrl: undefined,
    verified: true,
    badge: "Grains",
    location: "Gulu District",
    rating: 4.8,
    reviews: 142,
    price: "UGX 850/kg",
    produce: ["Maize", "Soya", "Millet"],
    online: true,
  },
  {
    id: 2,
    name: "Nakato Sarah",
    avatar: "NS",
    verified: true,
    badge: "Vegetables",
    location: "Wakiso District",
    rating: 4.9,
    reviews: 67,
    price: "UGX 1,200/kg",
    produce: ["Tomatoes", "Onions", "Pepper"],
    online: false,
  },
  {
    id: 3,
    name: "Tumuhaise Peter",
    avatar: "TP",
    verified: true,
    badge: "Herbs",
    location: "Mbarara District",
    rating: 5.0,
    reviews: 89,
    price: "UGX 25,000/L",
    produce: ["Honey", "Vanilla", "Ginger"],
    online: true,
  },
  {
    id: 4,
    name: "Akello Grace",
    avatar: "AG",
    verified: false,
    badge: "Roots",
    location: "Kabale District",
    rating: 4.7,
    reviews: 31,
    price: "UGX 600/kg",
    produce: ["Potatoes", "Cassava", "Sweet Potato"],
    online: false,
  },
]



export const products: Product[] = [
  {
    id: 1,
    name: "Grade A Maize",
    farmer: "Okello James",
    img: "🌽",
    badge: "Fresh",
    price: "UGX 850/kg",
    rating: 4.8,
    qty: "5,000 kg available",
  },
  {
    id: 2,
    name: "Fresh Tomatoes",
    farmer: "Nakato Sarah",
    img: "🍅",
    badge: "Organic",
    price: "UGX 1,200/kg",
    rating: 4.9,
    qty: "800 kg available",
  },
  {
    id: 3,
    name: "Organic Honey",
    farmer: "Tumuhaise Peter",
    img: "🍯",
    price: "UGX 25,000/L",
    rating: 5.0,
    qty: "200 litres available",
  },
  {
    id: 4,
    name: "Irish Potatoes",
    farmer: "Akello Grace",
    img: "🥔",
    badge: "Fresh",
    price: "UGX 600/kg",
    rating: 4.7,
    qty: "12,000 kg available",
  },
  {
    id: 5,
    name: "Vanilla Pods",
    farmer: "Birungi Joyce",
    img: "🌿",
    badge: "Premium",
    price: "UGX 180,000/kg",
    rating: 4.9,
    qty: "50 kg available",
  },
  {
    id: 6,
    name: "Fresh Milk",
    farmer: "Rwabwogo Daniel",
    img: "🥛",
    badge: "Fresh",
    price: "UGX 1,500/L",
    rating: 4.8,
    qty: "500 litres available",
  },
]