export type SellStep = "info" | "pricing" | "photos" | "publish";

export const SELL_STEPS: { key: SellStep; label: string }[] = [
  { key: "info", label: "Product Info" },
  { key: "pricing", label: "Pricing" },
  { key: "photos", label: "Photos" },
  { key: "publish", label: "Publish" },
];

export const PRODUCT_UNITS = ["kg", "litre", "bag", "crate", "bunch", "piece", "tonne"] as const;
export type ProductUnit = (typeof PRODUCT_UNITS)[number];

export const PRODUCT_CATEGORIES = [
  "Grains",
  "Vegetables",
  "Fruits",
  "Herbs",
  "Dairy",
  "Poultry",
  "Livestock",
  "Fish",
  "Other",
] as const;
export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

export const UGANDA_DISTRICTS = [
  "Kampala",
  "Wakiso",
  "Mukono",
  "Jinja",
  "Mbale",
  "Gulu",
  "Lira",
  "Mbarara",
  "Masaka",
  "Kabale",
  "Fort Portal",
  "Soroti",
  "Arua",
  "Hoima",
  "Tororo",
  "Iganga",
  "Busia",
  "Moroto",
  "Kotido",
  "Bundibugyo",
  "Kasese",
  "Kyenjojo",
  "Kamuli",
  "Bugiri",
  "Pallisa",
  "Kumi",
  "Kapchorwa",
  "Nebbi",
  "Adjumani",
  "Moyo",
  "Yumbe",
  "Koboko",
  "Maracha",
  "Other",
] as const;

// ─── Sell listing draft ───────────────────────────────────────────────────────

export interface SellListingDraft {
  // Step 1 — Product info
  name: string;
  category: ProductCategory | "";
  district: string;
  village: string;
  description: string;
  tags: string; // comma-separated

  // Step 2 — Pricing
  price: string; // kept as string for input control
  unit: ProductUnit;
  totalQty: string;
  minimumOrder: string;
  fresh: boolean;
  // Bulk pricing tiers
  enableTiers: boolean;
  tier2MinQty: string;
  tier2Price: string;
  tier3MinQty: string;
  tier3Price: string;

  // Step 3 — Photos
  // File objects — not persisted (can't serialize File to localStorage)
  photoFiles: File[];
  // Preview object URLs — generated client-side for display
  photoPreviews: string[];
}

// ─── What gets sent to the backend ───────────────────────────────────────────
// Your FastAPI endpoint receives multipart/form-data.
// Images go as File objects; everything else as JSON string fields.

export interface CreateListingPayload {
  name: string;
  category: string;
  district: string;
  village: string;
  description: string;
  tags: string[];
  price: number;
  unit: string;
  totalQty: number;
  minimumOrder: number;
  fresh: boolean;
  priceTiers?: { minQty: number; price: number; label: string }[];
  // Images go as files in FormData — backend generates URLs
  images: File[];
}

// ─── Backend response after successful listing ────────────────────────────────

export interface CreateListingResponse {
  id: string | number;
  slug: string;
  imageUrls: string[]; // URLs generated by backend after upload
  message: string;
}

// ─── AI price suggestion (from backend) ──────────────────────────────────────

export interface AiPriceSuggestion {
  min: number;
  max: number;
  suggested: number;
  basis: string; // e.g. "Based on 47 recent listings in Gulu"
}
